package factoryEnvironment;

public enum EnvironmentList {
	DEV, TESTING, STAGING, PRODUCTION, FACEBOOK,JQUERYDATATABLE1,JQUERYDATATABLE2, JQUERYUPLOAD, WORDPRESSUSER, WORDPRESSADMIN, LIVEGURU, NOPCOMMERCEUSER, NOPCOMMERCEADMIN, SAUCELAB  ;


}
